# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build app and Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_app:
    name: Build and commit Nitro assets
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm ci
    - name: Build Nitro assets
      run: npm run build
    - name: Commit built assets
      uses: stefanzweifel/git-auto-commit-action@v4.16.0
      with:
        commit_message: Nitro assets built

  build_docker_image:
    name: Build and publish Docker image
    needs: [build_app]
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: cyrilschreiber/ddns-updater:latest
